services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgresql://vpsdepati:Vpsdepati.123!@db-host:5432/pesonakebaikan?schema=public"
        DOKU_CLIENT_ID: ${DOKU_CLIENT_ID}
        DOKU_SECRET_KEY: ${DOKU_SECRET_KEY}
        DOKU_IS_PRODUCTION: ${DOKU_IS_PRODUCTION:-true}
        NEXT_PUBLIC_MIN_DONATION: 10
    container_name: pesonakebaikan-app
    ports:
      - "9000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "db-host:host-gateway"
    env_file:
      - .env

    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://vpsdepati:Vpsdepati.123!@db-host:5432/pesonakebaikan?schema=public"
    restart: unless-stopped
