import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";
import SimpleAppBar from "@/components/AppBar";
import SimpleBottomNavigation from "@/components/BottomNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <div className="flex min-h-screen items-center justify-center bg-gray-100 dark:bg-gray-900">
            <div className="relative w-full max-w-md h-screen max-h-screen bg-white dark:bg-black rounded-2xl shadow-2xl overflow-hidden flex flex-col">
              <SimpleAppBar />
              <div className="flex-1 overflow-y-auto">{children}</div>
              <SimpleBottomNavigation />
            </div>
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
